contentDir = "content"
layoutDir = "themes/hugo-paper-bj/layouts/"
themesDir = "themes"
theme = "hugo-paper-bj"
staticDir = "themes/hugo-paper-bj/static/"
baseURL = "www.brianjoseff.com/"
languageCode = "en-us"
title = "Brian Joseff"
googleAnalytics = "UA-100593457-1"