contentDir = "content"
layoutDir = "themes/hugo-paper/layouts/"
themesDir = "themes"
theme = "hugo-paper"
staticDir = "themes/hugo-paper/static/"
baseURL = "https://www.brianjoseff.com/"
languageCode = "en-us"
title = "Brian Joseff"
googleAnalytics = "UA-100593457-1"