contentDir = "content"
layoutDir = "themes/monad/layouts"
themesDir = "themes"
theme = "monad"
staticDir = "themes/monad/static"
baseURL = "https://brianjoseff.com"
languageCode = "en-us"
title = "Brian Joseff"
